import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import ClientRootLayout from "@/components/common/ClientRootLayout";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${poppins.variable} bg-background font-sans antialiased`}
      >
        <ClientRootLayout defaultOpen={defaultOpen}>{children}</ClientRootLayout>
      </body>
    </html>
  );
}
